name: "build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:

jobs:
  call-build:
    uses: "powercasgamer/.github/.github/workflows/shared-ci.yml@master"
    secrets: "inherit"
    #with:
    #  artifacts-path: ''
    #  jdk-version: 17
    #  main-branch: 'main'
    #  validate-gradle-wrapper: true
    #  init-submodules: false
    #  setup-gradle: true
    #  loom: true
    #  paperweight: true
    #  vanillagradle: true